package wgconfig

import (
	"fmt"
	"net/netip"
	"regexp"
	"strconv"
	"strings"

	"wireguard-panel/internal/model"
)

var unsafeFilenameCharacters = regexp.MustCompile(`[^A-Za-z0-9._-]+`)

func (store *Store) ClientConfig(
	interfaceID int,
	peerID string,
) (string, []byte, error) {
	store.mu.RLock()
	defer store.mu.RUnlock()
	config, err := store.readLocked(interfaceID)
	if err != nil {
		return "", nil, err
	}
	index := peerIndex(config.Peers, peerID)
	if index < 0 {
		return "", nil, ErrPeerNotFound
	}
	filename, data, err := buildClientConfig(config, config.Peers[index])
	return filename, data, err
}

func buildClientConfig(
	config model.Interface,
	peer model.Peer,
) (string, []byte, error) {
	if peer.PrivateKey == "" {
		return "", nil, fmt.Errorf(
			"%w: 此 Peer 没有保存在服务端的 PrivateKey",
			ErrClientConfigMissing,
		)
	}
	if config.ClientEndpoint == "" {
		return "", nil, fmt.Errorf(
			"%w: Interface 尚未配置 ClientEndpoint",
			ErrClientConfigMissing,
		)
	}
	addresses := peer.ClientAddress
	if len(addresses) == 0 {
		addresses = hostAllowedIPs(peer.AllowedIPs)
	}
	if len(addresses) == 0 {
		return "", nil, fmt.Errorf(
			"%w: Peer 尚未配置 ClientAddress",
			ErrClientConfigMissing,
		)
	}
	serverPublicKey, err := PublicKeyFromPrivate(config.PrivateKey)
	if err != nil {
		return "", nil, err
	}
	allowedIPs := config.ClientAllowedIPs
	if len(allowedIPs) == 0 {
		allowedIPs = interfaceNetworks(config.Address)
	}
	if len(allowedIPs) == 0 {
		return "", nil, fmt.Errorf(
			"%w: Interface 尚未配置客户端 AllowedIPs，且 Address 无法推导子网",
			ErrClientConfigMissing,
		)
	}
	keepalive := peer.ClientPersistentKeepalive
	if keepalive == nil {
		keepalive = config.ClientPersistentKeepalive
	}

	var output strings.Builder
	output.WriteString("# Generated by WireGuard Panel\n")
	writeComment(&output, "Name", peer.Name)
	output.WriteString("[Interface]\n")
	writeField(&output, "PrivateKey", peer.PrivateKey)
	writeList(&output, "Address", addresses)
	writeList(&output, "DNS", config.ClientDNS)
	if config.MTU != nil {
		writeField(&output, "MTU", strconv.Itoa(*config.MTU))
	}
	output.WriteString("\n[Peer]\n")
	writeField(&output, "PublicKey", serverPublicKey)
	writeField(&output, "PresharedKey", peer.PresharedKey)
	writeList(&output, "AllowedIPs", allowedIPs)
	writeField(&output, "Endpoint", config.ClientEndpoint)
	if keepalive != nil {
		writeField(
			&output,
			"PersistentKeepalive",
			strconv.FormatUint(uint64(*keepalive), 10),
		)
	}

	name := unsafeFilenameCharacters.ReplaceAllString(peer.Name, "-")
	name = strings.Trim(name, "-._")
	if name == "" {
		name = peer.ID
	}
	return fmt.Sprintf("%s-%s.conf", strings.TrimSuffix(config.Filename, ".conf"), name),
		[]byte(output.String()),
		nil
}

func hostAllowedIPs(values []string) []string {
	result := make([]string, 0)
	for _, value := range values {
		prefix, err := netip.ParsePrefix(value)
		if err != nil || !isHostPrefix(prefix) {
			continue
		}
		result = append(result, prefix.String())
	}
	return result
}

func interfaceNetworks(values []string) []string {
	result := make([]string, 0)
	seen := make(map[string]bool)
	for _, value := range values {
		prefix, err := netip.ParsePrefix(value)
		if err != nil {
			continue
		}
		network := normalizedPrefix(prefix).String()
		if !seen[network] {
			seen[network] = true
			result = append(result, network)
		}
	}
	return result
}
