package wgconfig

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"wireguard-panel/internal/model"
)

func TestGeneratedPeerMetadataClientConfigAndRevisionConflict(t *testing.T) {
	directory := t.TempDir()
	store, err := NewStore(directory)
	if err != nil {
		t.Fatal(err)
	}
	config, err := store.Create("Office", model.InterfaceInput{
		PrivateKey:       testPrivateKey(t),
		Address:          []string{"10.60.0.1/24"},
		ClientEndpoint:   "vpn.example.com:51820",
		ClientAllowedIPs: []string{"10.60.0.0/24", "fd60::/64"},
	})
	if err != nil {
		t.Fatal(err)
	}
	originalRevision := config.Revision
	peerPrivateKey, peerPublicKey, err := GenerateKeyPair()
	if err != nil {
		t.Fatal(err)
	}
	presharedKey, err := GeneratePresharedKey()
	if err != nil {
		t.Fatal(err)
	}
	config, err = store.AddPeer(config.ID, config.Revision, model.PeerInput{
		Name:         "Alice Laptop",
		PrivateKey:   peerPrivateKey,
		PublicKey:    peerPublicKey,
		PresharedKey: presharedKey,
		AllowedIPs:   []string{"10.60.0.2/32", "fd60::2/128"},
	})
	if err != nil {
		t.Fatal(err)
	}
	if config.Revision == originalRevision {
		t.Fatal("revision did not change after peer creation")
	}
	if len(config.Peers) != 1 {
		t.Fatalf("unexpected peers: %#v", config.Peers)
	}
	peer := config.Peers[0]
	if peer.PrivateKey == "" ||
		peer.PublicKey == "" ||
		peer.PresharedKey == "" {
		t.Fatalf("generated peer is incomplete: %#v", peer)
	}
	derived, err := PublicKeyFromPrivate(peer.PrivateKey)
	if err != nil || derived != peer.PublicKey {
		t.Fatalf("stored key pair does not match: derived=%q err=%v", derived, err)
	}

	native, err := os.ReadFile(filepath.Join(directory, "Office.conf"))
	if err != nil {
		t.Fatal(err)
	}
	for _, expected := range []string{
		"# ClientEndpoint = vpn.example.com:51820",
		"# ClientAllowedIPs = 10.60.0.0/24, fd60::/64",
		"# Name = Alice Laptop",
		"# PrivateKey = " + peer.PrivateKey,
		"PublicKey = " + peer.PublicKey,
	} {
		if !strings.Contains(string(native), expected) {
			t.Errorf("native configuration is missing %q:\n%s", expected, native)
		}
	}
	if strings.Contains(string(native), "# ID =") {
		t.Fatalf("native configuration contains obsolete Peer ID metadata:\n%s", native)
	}
	filename, client, err := store.ClientConfig(config.ID, peer.PublicKey)
	if err != nil {
		t.Fatal(err)
	}
	if filename != "Office-Alice-Laptop.conf" {
		t.Fatalf("unexpected client filename %q", filename)
	}
	for _, expected := range []string{
		"[Interface]",
		"PrivateKey = " + peer.PrivateKey,
		"Address = 10.60.0.2/32",
		"[Peer]",
		"PresharedKey = " + peer.PresharedKey,
		"AllowedIPs = 10.60.0.0/24, fd60::/64",
		"Endpoint = vpn.example.com:51820",
		"PersistentKeepalive = 25",
	} {
		if !strings.Contains(string(client), expected) {
			t.Errorf("client configuration is missing %q:\n%s", expected, client)
		}
	}
	if strings.Contains(string(client), "DNS =") {
		t.Fatalf("client configuration must not contain DNS:\n%s", client)
	}
	for _, unexpected := range []string{
		"# Generated by WireGuard Panel",
		"# Name =",
	} {
		if strings.Contains(string(client), unexpected) {
			t.Fatalf("client configuration must not contain %q:\n%s", unexpected, client)
		}
	}
	if strings.Contains(string(client), "Address = 10.60.0.2/32,") ||
		strings.Contains(string(client), "Address = fd60::2/128") {
		t.Fatalf("client Address must use only the first AllowedIPs entry:\n%s", client)
	}

	_, err = store.Update(config.ID, originalRevision, interfaceInput(config))
	if !errors.Is(err, ErrRevisionConflict) {
		t.Fatalf("stale revision returned %v", err)
	}
}

func TestClientConfigPreviewKeepsRequiredAndOmitsOptionalMissingFields(t *testing.T) {
	_, client, err := buildClientConfig(
		model.Interface{Filename: "wg0.conf"},
		model.Peer{Name: "Incomplete", PublicKey: testPublicKey(t)},
	)
	if err != nil {
		t.Fatalf("incomplete client preview returned %v", err)
	}
	for _, required := range []string{
		"PrivateKey =\n",
		"PublicKey =\n",
	} {
		if !strings.Contains(string(client), required) {
			t.Errorf("incomplete client preview must keep %q:\n%s", required, client)
		}
	}
	for _, omitted := range []string{
		"Address =",
		"PresharedKey =",
		"AllowedIPs =",
		"Endpoint =",
	} {
		if strings.Contains(string(client), omitted) {
			t.Errorf("incomplete client preview must omit %q:\n%s", omitted, client)
		}
	}
}

func TestClientConfigDoesNotInheritServerMTU(t *testing.T) {
	mtu := 1420
	_, client, err := buildClientConfig(
		model.Interface{Filename: "wg0.conf", MTU: &mtu},
		model.Peer{Name: "Client", PublicKey: testPublicKey(t)},
	)
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(client), "MTU =") {
		t.Fatalf("client configuration inherited the server MTU:\n%s", client)
	}
}

func TestClientConfigUsesFirstAddressInsideNetworkPrefix(t *testing.T) {
	_, ipv4, err := buildClientConfig(
		model.Interface{Filename: "wg0.conf"},
		model.Peer{Name: "IPv4", PublicKey: testPublicKey(t), AllowedIPs: []string{"10.70.0.0/24"}},
	)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(ipv4), "Address = 10.70.0.1/24") {
		t.Fatalf("IPv4 client did not use the first address in its CIDR:\n%s", ipv4)
	}

	_, ipv6, err := buildClientConfig(
		model.Interface{Filename: "wg0.conf"},
		model.Peer{Name: "IPv6", PublicKey: testPublicKey(t), AllowedIPs: []string{"fd70::/64"}},
	)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(ipv6), "Address = fd70::1/64") {
		t.Fatalf("IPv6 client did not use the first address in its CIDR:\n%s", ipv6)
	}
}

func TestClientConfigUsesListenPortForHostOnlyEndpoint(t *testing.T) {
	listenPort := uint16(51820)
	for _, test := range []struct {
		endpoint string
		want     string
	}{
		{endpoint: "vpn.example.com", want: "Endpoint = vpn.example.com:51820"},
		{endpoint: "192.0.2.10", want: "Endpoint = 192.0.2.10:51820"},
		{endpoint: "2001:db8::10", want: "Endpoint = [2001:db8::10]:51820"},
		{endpoint: "[2001:db8::10]", want: "Endpoint = [2001:db8::10]:51820"},
		{endpoint: "vpn.example.com:20000", want: "Endpoint = vpn.example.com:20000"},
	} {
		_, client, err := buildClientConfig(
			model.Interface{
				Filename:       "wg0.conf",
				ListenPort:     &listenPort,
				ClientEndpoint: test.endpoint,
			},
			model.Peer{Name: "Client", PublicKey: testPublicKey(t)},
		)
		if err != nil {
			t.Fatalf("ClientEndpoint %q returned %v", test.endpoint, err)
		}
		if !strings.Contains(string(client), test.want) {
			t.Errorf("ClientEndpoint %q did not produce %q:\n%s", test.endpoint, test.want, client)
		}
	}
}

func TestIPPlanAndConflictingPeerAssignments(t *testing.T) {
	store, err := NewStore(t.TempDir())
	if err != nil {
		t.Fatal(err)
	}
	config, err := store.Create("Plan", model.InterfaceInput{
		PrivateKey: testPrivateKey(t),
		Address:    []string{"10.70.0.1/29", "fd70::1/64"},
	})
	if err != nil {
		t.Fatal(err)
	}
	plan, err := store.IPPlan(config.ID)
	if err != nil {
		t.Fatal(err)
	}
	if len(plan.Networks) != 2 ||
		plan.Revision != config.Revision ||
		plan.Networks[0].SuggestedAddress != "10.70.0.2/29" ||
		plan.Networks[0].SuggestedAllowedIP != "10.70.0.2/32" {
		t.Fatalf("unexpected initial IP plan: %#v", plan)
	}

	config, err = store.AddPeer(config.ID, config.Revision, model.PeerInput{
		Name:       "Peer A",
		PublicKey:  testPublicKey(t),
		AllowedIPs: []string{"10.70.0.2/32"},
	})
	if err != nil {
		t.Fatal(err)
	}
	plan, err = store.IPPlan(config.ID)
	if err != nil {
		t.Fatal(err)
	}
	if plan.Networks[0].SuggestedAddress != "10.70.0.3/29" {
		t.Fatalf("allocated address was not skipped: %#v", plan.Networks[0])
	}
	if plan.Revision != config.Revision {
		t.Fatalf("updated IP plan revision %q does not match config %q", plan.Revision, config.Revision)
	}

	_, err = store.AddPeer(config.ID, config.Revision, model.PeerInput{
		Name:       "Peer B",
		PublicKey:  testPublicKey(t),
		AllowedIPs: []string{"10.70.0.2/32"},
	})
	if !errors.Is(err, ErrConflict) {
		t.Fatalf("conflicting IP assignment returned %v", err)
	}

	_, err = store.AddPeer(config.ID, config.Revision, model.PeerInput{
		Name:       "Interface collision",
		PublicKey:  testPublicKey(t),
		AllowedIPs: []string{"10.70.0.1/32"},
	})
	if !errors.Is(err, ErrConflict) || !strings.Contains(err.Error(), "Interface Address") {
		t.Fatalf("Interface address collision returned %v", err)
	}
}

func TestGenerateKeyPairProducesMatchingWireGuardKeys(t *testing.T) {
	privateKey, publicKey, err := GenerateKeyPair()
	if err != nil {
		t.Fatal(err)
	}
	derived, err := PublicKeyFromPrivate(privateKey)
	if err != nil {
		t.Fatal(err)
	}
	if derived != publicKey {
		t.Fatalf("derived public key %q does not match %q", derived, publicKey)
	}
	_, err = NormalizePeer(model.PeerInput{
		PrivateKey: privateKey,
		PublicKey:  testPublicKey(t),
	})
	if err == nil {
		t.Fatal("mismatched key pair was accepted")
	}
	_, err = preparePeerInput(model.PeerInput{PrivateKey: privateKey})
	if !errors.Is(err, ErrInvalidInput) {
		t.Fatalf("Peer without required PublicKey returned %v", err)
	}
	_, err = PublicKeyFromPrivate("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB=")
	if !errors.Is(err, ErrInvalidInput) {
		t.Fatalf("non-canonical PrivateKey returned %v", err)
	}
}
